[package]
name = "proxymuxer"
version = "0.2.1"
edition = "2021"
authors = ["Bart Noordervliet <bart@mmvi.nl>"]

[dependencies]
yaml-rust = "0"
regex = "1"
signal-hook = "0"
crossbeam-channel = "0"
nix = { version = "0", features = [ "process" ]}
